#Emri i aplikacionit Spring
spring.application.name=connection

#URL e databazes MySQL qe do te perdore aplikacioni
#porta 3306 eshte default per mysql
spring.datasource.url=jdbc:mysql://localhost:3306/spring_demo
spring.datasource.username=root
spring.datasource.password=Athina21!

#driveri jdbc qe perdoret per te komunikuar me mysql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#si do te sillet hibernate me strukturen e tabelave ne databaze
#update do te thote qe nese entitetet ndryshojne
#hibernate do te bej automatikisht update tabelat ne mysql
spring.jpa.hibernate.ddl-auto=update

#shfaq querit sql qe ekzekutohne ne console
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect